server:
  port: 18081
  servlet:
    contextPath: /bullcontrol/api
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
spring:
  jackson:
    parser:
      ALLOW_COMMENTS: true
bullcontrol-api:
  username: bullcontrol-api
  bullcontrol:
    url: http://localhost:8080/bullcontrol
  locale:
    country: BR
    language: pt
management:
  endpoints:
    jmx:
      exposure:
        include: health
    web:
      exposure:
        include: health
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG